### ISSUE TITLE
[Route53] Check TXT Record fails on the apex domain.

### ISSUE THREAD

**Issue by kitsunde** [k1LoW/certman#11]
I love that I found this when I was thinking if I could do the exact same thing. I ran into an issue though:

```
$ AWS_DEFAULT_REGION=us-east-1 certman request fairmontsingaporenightrace.com
NOTICE! Your selected region is *us-east-1*. Certman create certificate on *us-east-1*. OK? Yes
NOTICE! When requesting, Certman replace Active Receipt Rule Set. OK? Yes
[/] [ACM] Check Certificate (us-east-1)
[✔] [ACM] Check Certificate (us-east-1) (successfull)
[✔] [Route53] Check Hosted Zone (us-east-1) (successfull)
[\] [Route53] Check TXT Record (us-east-1)/Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/certman-0.4.0/lib/certman/resource/route53.rb:123:in `check_txt_rset': _amazonses.fairmontsingaporenightrace.com TXT already exist (RuntimeError)
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/certman-0.4.0/lib/certman/client.rb:87:in `check_resource'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/certman-0.4.0/lib/certman/client.rb:17:in `request'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/certman-0.4.0/lib/certman/cli.rb:20:in `request'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/gems/certman-0.4.0/exe/certman:7:in `<top (required)>'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/bin/certman:22:in `load'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/bin/certman:22:in `<main>'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kitsunde/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

`_amazonses.fairmontsingaporenightrace.com` didn't exist. I've tried:

* Adding it through the SES wizard.
* Using a different much shorter domain like venilia.co
* Downgrading to 0.3.0
* Using my system default region (Singapore)

It all comes back like this. Any idea what's going on?

**Comment by kitsunde** [comment]
Right. The issue is that it doesn't like apex domains.

```
certman request www.fairmontsingaporenightrace.com
```

Appears to be working. How do I request a cert for the root?
